language: ruby
cache: bundler
sudo: false

before_install:
  - gem update bundler

notifications:
  email:
    on_success: never
    on_failure: never

matrix:
  fast_finish: true

rvm:
  - 2.5
  - 2.6
  - 2.7
   
gemfile:
  - gemfiles/ar_5.2.gemfile
  - gemfiles/ar_6.0.gemfile

env:
  global:
    - TRAVIS=true
  matrix:
    - DB=mysql
    - DB=postgres
    - DB=sqlite

before_script:
  - mysql --version
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql   -e 'create database paper_trail_test;'; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql   -e 'create database paper_trail_bar; '; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql   -e 'create database paper_trail_foo; '; fi"
  - psql --version
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_bar;'  -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_foo;'  -U postgres; fi"
